; Script generated by Google Antigravity for Inno Setup (Full App with Local OCR)
; Instructions: Download Inno Setup (https://jrsoftware.org/isdl.php), open this file with Inno Setup Compiler, and click 'Compile'.

#define MyAppName "Police Project"
#define MyAppVersion "1.0.0"
#define MyAppPublisher "Police Project Team"
#define MyAppExeName "PoliceLauncher.exe"

[Setup]
AppId={{D9A83F12-87C2-4B6A-91E3-87B11F247A9B}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
AppPublisher={#MyAppPublisher}
DefaultDirName={autopf}\PoliceProject
DefaultGroupName={#MyAppName}
OutputDir=build_installer
OutputBaseFilename=PoliceProject_Setup_v1.0.0
Compression=lzma2/ultra64
SolidCompression=yes
WizardStyle=modern
PrivilegesRequired=lowest

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked

[Files]
; Package Launcher Executable, Backend, and Frontend
Source: "PoliceLauncher.exe"; DestDir: "{app}"; Flags: ignoreversion
Source: "start-app.bat"; DestDir: "{app}"; Flags: ignoreversion
Source: "stop-app.bat"; DestDir: "{app}"; Flags: ignoreversion
Source: "backend\*"; DestDir: "{app}\backend"; Flags: ignoreversion recursesubdirs createallsubdirs; Excludes: "node_modules, *.log"
Source: "frontend\*"; DestDir: "{app}\frontend"; Flags: ignoreversion recursesubdirs createallsubdirs; Excludes: "node_modules, .next, *.log"

[Icons]
Name: "{group}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; IconFilename: "{app}\frontend\src\app\favicon.ico"
Name: "{group}\Uninstall {#MyAppName}"; Filename: "{uninstallexe}"
Name: "{autodesktop}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; IconFilename: "{app}\frontend\src\app\favicon.ico"; Tasks: desktopicon

[Run]
Filename: "{app}\{#MyAppExeName}"; Description: "เปิดใช้งาน {#MyAppName} ทันที"; Flags: postinstall shellexec skipifsilent
